### PR TITLE
fix build for vala 0.32

### PR DESCRIPTION
**Pull request by marguerite**

### CODE REVIEW

**Comment by ueno** [comment]
Thank you, merged.  The CI failure should be fixed with the latest git master.

**Comment by ueno** [comment]
It seems that the commit c892213 is still causing failure in ```make check```:
https://travis-ci.org/ueno/libkkc/builds/215564993
How is this ```new``` keyword supposed to work?

**Comment by marguerite** [comment]
Hi, @ueno 

I just followed the upstream tutorial for the 'new' operator:

"Reference types are instantiated using the new operator and the name of a construction method, which is usually just the name of the type, e.g. Object o = new Object() creates a new Object and makes o a reference to it."

https://wiki.gnome.org/Projects/Vala/Tutorial

There's no any further documents about the usage of the 'new' op (maybe because it's too easy?)

And there's only one previous commit about fixing this kind of error on the internet:

https://github.com/pdfpc/pdfpc/commit/108b1d7c59e3754732c225a4376a6faee1ad2b0d

**Comment by marguerite** [comment]
btw, the vala you use in travis is 0.24...maybe due to that?

but I can't find the upstream commit that enforces the usage of 'new' op...so no way to tell if it is backward compatible

**Comment by ueno** [comment]
Before landing this PR, I updated the CI to use a docker image, where vala 0.34.6 is installed (i.e. Fedora 25):
https://travis-ci.org/ueno/libkkc/builds/215562501

Interestingly, it compiles without a ```new``` before the non-default constructor call and passes all tests.

**Comment by marguerite** [comment]
@ueno please see this commit: 

https://github.com/GNOME/vala/commit/73b9e4b4a2c059ceb6bce7ab173050fb70739892

this is the only commit that has changes related with the warning message since 2011...I know little about vala, but hope it may give you some hints...

**Comment by marguerite** [comment]
openSUSE Tumbleweed is using 0.36.0 and fails.

the previous commit happens between 0.35.x to 0.36...so I used a wrong version flag...

I was mislead by https://bugs.launchpad.net/pantheon-files/+bug/1284692

but since that warning message exists for long, it is actually an unrelated other problem.

the only relevant issue is on debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819858;msg=2

and it is fixed this way.

**Comment by ueno** [comment]
Could you paste the actual warning you get with Kkc.KeyEvent?  I am suspecting you might be confused with Gdk.EventKey (it's a boxed type, while Kkc.KeyEvent is a GObject type), as I haven't ever seen this.

I have compared generated key-event.c with and without the ```new``` operator.  With ```new```, Vala 0.34.6 generates invalid code:
```c
KkcKeyEvent* kkc_key_event_construct_from_string (GType object_type, const gchar* key, GError** error) {
...
	_tmp98_ = kkc_key_event_new_from_x_event (_tmp96_, (guint) 0, _tmp97_);
	_tmp99_ = _tmp98_;
	_g_object_unref0 (_tmp99_); /* <-- */
	return self;
}
```
Here the created instance is unref'ed before returning.  I guess this is a corner-case bug in Vala, but I'd say it's wrong to use ```new``` here.

**Comment by ueno** [comment]
I am reverting this with #5.

**Comment by marguerite** [comment]
@ueno 

        [   55s]   VALAC    libkkc_la_vala.stamp
        [   56s] candidate-list.vala:93.20-93.43: warning: Gee.Map.contains is deprecated. Use Map.has_key
        [   56s] candidate-list.vala:97.17-97.40: warning: Gee.Map.contains is deprecated. Use Map.has_key
        [   56s] key-event.vala:151.13-151.49: error: use `new' operator to create new objects
        [   56s]             from_x_event (_keyval, 0, _modifiers);
        [   56s]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [   56s] Compilation failed: 1 error(s), 2 warning(s)

it wasn't "an actual warning"...it was an error, key-event.c even can't be generated :-(

Marguerite

**Comment by ueno** [comment]
I was able to reproduce it with the latest git master of Vala.  #6 should fix the issue for both 0.34 and 0.36.

**Comment by marguerite** [comment]
@ueno Thank you so much!

**Pull request merged**
